"""initial_schema

Revision ID: 2e3bd6785936
Revises: 
Create Date: 2026-05-13 18:17:04.743821

Bootstrap ordering (2026-05-14): ``pay_periods.locked_by_payroll_run_id`` FK and
``payroll_runs`` user FKs are created via ``op.create_foreign_key`` after dependent
tables exist, so ``alembic upgrade`` succeeds on PostgreSQL (no circular / forward FK).

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2e3bd6785936'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_idempotency_keys',
    sa.Column('id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False),
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('method', sa.String(length=10), server_default=sa.text("'POST'"), nullable=False),
    sa.Column('path', sa.String(length=255), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('status_code', sa.Integer(), server_default=sa.text('(200)'), nullable=False),
    sa.Column('response_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("('{}'::jsonb)"), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organisation_id', 'key', name='ux_api_idempo_org_key')
    )
    op.create_table('organisations',
    sa.Column('organisation_id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('legal_name', sa.Text(), nullable=True),
    sa.Column('registration_no', sa.Text(), nullable=True),
    sa.Column('tax_id', sa.String(length=100), nullable=True),
    sa.Column('pan', sa.String(length=20), nullable=True),
    sa.Column('tds_circle', sa.String(length=100), nullable=True),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), server_default=sa.text("'India'"), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('timezone', sa.String(length=50), server_default=sa.text("'Asia/Kolkata'"), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_setup_complete', sa.Boolean(), server_default=sa.text('(false)'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('(true)'), nullable=False),
    sa.Column('hr_settings', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("('{}'::jsonb)"), nullable=False),
    sa.PrimaryKeyConstraint('organisation_id')
    )
    op.create_table('pay_periods',
    sa.Column('pay_period_id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False),
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'open'"), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('attendance_leave_locked', sa.Boolean(), server_default=sa.text('(false)'), nullable=False),
    sa.Column('locked_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('locked_by_payroll_run_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.organisation_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pay_period_id'),
    sa.UniqueConstraint('organisation_id', 'start_date', 'end_date', name='ux_pay_periods_org_dates')
    )
    op.create_table('payroll_runs',
    sa.Column('payroll_run_id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False),
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('pay_period_id', sa.UUID(), nullable=False),
    sa.Column('processed_by', sa.UUID(), nullable=True),
    sa.Column('processed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'draft'"), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('gross_pay_total', sa.Numeric(precision=18, scale=2), server_default=sa.text('0'), nullable=True),
    sa.Column('net_pay_total', sa.Numeric(precision=18, scale=2), server_default=sa.text('0'), nullable=True),
    sa.Column('execution_trace_id', sa.UUID(), nullable=True),
    sa.Column('execution_meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('execution_status', sa.String(length=32), server_default=sa.text("'draft'"), nullable=False),
    sa.Column('lifecycle_status', sa.String(length=32), nullable=True),
    sa.Column('lifecycle_verified_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('lifecycle_verified_by', sa.UUID(), nullable=True),
    sa.Column('lifecycle_approved_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('lifecycle_approved_by', sa.UUID(), nullable=True),
    sa.Column('payroll_locked_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('lifecycle_locked_by', sa.UUID(), nullable=True),
    sa.Column('final_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.organisation_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pay_period_id'], ['pay_periods.pay_period_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('payroll_run_id')
    )
    # pay_periods -> payroll_runs (optional lock pointer): created after both tables exist
    op.create_foreign_key(
        'fk_pay_periods_locked_by_run',
        'pay_periods',
        'payroll_runs',
        ['locked_by_payroll_run_id'],
        ['payroll_run_id'],
        ondelete='SET NULL',
    )
    op.create_table('departments',
    sa.Column('department_id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False),
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('(true)'), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.organisation_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('department_id'),
    sa.UniqueConstraint('organisation_id', 'name', name='ux_departments_org_name')
    )
    op.create_table('designations',
    sa.Column('designation_id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False),
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('level', sa.SmallInteger(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('(true)'), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.organisation_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('designation_id'),
    sa.UniqueConstraint('organisation_id', 'title', name='ux_designations_org_title')
    )
    op.create_table('org_statutory_configs',
    sa.Column('config_id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False),
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('statutory_code', sa.String(length=20), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), server_default=sa.text('(true)'), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("('{}'::jsonb)"), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('effective_to IS NULL OR effective_to >= effective_from', name='ck_org_statutory_configs_effective_range'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.organisation_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('config_id'),
    sa.UniqueConstraint('organisation_id', 'statutory_code', 'effective_from', name='ux_org_statutory_configs_org_code_from')
    )
    op.create_table('organisation_holidays',
    sa.Column('holiday_id', sa.UUID(), nullable=False),
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('holiday_date', sa.Date(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('is_optional', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.organisation_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('holiday_id'),
    sa.UniqueConstraint('organisation_id', 'holiday_date', name='ux_org_holiday_date')
    )
    op.create_index('ix_org_holidays_org_date', 'organisation_holidays', ['organisation_id', 'holiday_date'], unique=False)
    op.create_table('roles',
    sa.Column('role_id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False),
    sa.Column('organisation_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('builtin', sa.Boolean(), server_default=sa.text('(false)'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.organisation_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id'),
    sa.UniqueConstraint('organisation_id', 'name', name='ux_roles_org_name')
    )
    op.create_table('salary_component_groups',
    sa.Column('group_id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False),
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('(true)'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.organisation_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('group_id'),
    sa.UniqueConstraint('organisation_id', 'code', name='ux_salary_component_groups_org_code')
    )
    op.create_table('salary_components',
    sa.Column('component_id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False),
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('component_category', sa.String(length=30), nullable=True),
    sa.Column('calculation_type', sa.String(length=20), nullable=True),
    sa.Column('formula_expression', sa.Text(), nullable=True),
    sa.Column('system_code', sa.String(length=30), nullable=True),
    sa.Column('rounding_rule', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("('{}'::jsonb)"), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("('{}'::jsonb)"), nullable=False),
    sa.Column('component_type', sa.String(length=50), nullable=False),
    sa.Column('calc_type', sa.String(length=20), server_default=sa.text("'fixed'"), nullable=False),
    sa.Column('percentage_of', sa.String(length=100), nullable=True),
    sa.Column('formula', sa.Text(), nullable=True),
    sa.Column('rounding', sa.Numeric(precision=10, scale=4), server_default=sa.text('0'), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('(true)'), nullable=False),
    sa.Column('is_taxable', sa.Boolean(), server_default=sa.text('(true)'), nullable=False),
    sa.Column('is_pf_applicable', sa.Boolean(), server_default=sa.text('(false)'), nullable=False),
    sa.Column('is_allowance', sa.Boolean(), server_default=sa.text('(false)'), nullable=False),
    sa.Column('is_loan_related', sa.Boolean(), server_default=sa.text('(false)'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.organisation_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('component_id'),
    sa.UniqueConstraint('organisation_id', 'name', name='ux_salarycomponents_org_name')
    )
    op.create_table('salary_derived_variables',
    sa.Column('variable_id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False),
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('expression', sa.Text(), nullable=False),
    sa.Column('data_type', sa.String(length=10), server_default=sa.text("'number'"), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('(true)'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.organisation_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('variable_id'),
    sa.UniqueConstraint('organisation_id', 'code', name='ux_salary_derived_variables_org_code')
    )
    op.create_table('salary_templates',
    sa.Column('template_id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False),
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("('{}'::jsonb)"), nullable=False),
    sa.Column('is_default', sa.Boolean(), server_default=sa.text('(false)'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.organisation_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('template_id'),
    sa.UniqueConstraint('organisation_id', 'name', name='ux_salarytemplates_org_name')
    )
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False),
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('full_name', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'active'"), nullable=False),
    sa.Column('role', sa.String(length=20), server_default=sa.text("'admin'"), nullable=False),
    sa.Column('last_login', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_system_admin', sa.Boolean(), server_default=sa.text('(false)'), nullable=False),
    sa.Column('reset_token', sa.String(), nullable=True),
    sa.Column('reset_token_expiry', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.organisation_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('organisation_id', 'email', name='ux_users_org_email'),
    sa.UniqueConstraint('organisation_id', 'username', name='ux_users_org_username')
    )
    # payroll_runs -> users FKs deferred until users table exists (bootstrap ordering)
    op.create_foreign_key(
        'fk_payroll_runs_processed_by',
        'payroll_runs',
        'users',
        ['processed_by'],
        ['user_id'],
    )
    op.create_foreign_key(
        'fk_payroll_runs_lifecycle_verified_by',
        'payroll_runs',
        'users',
        ['lifecycle_verified_by'],
        ['user_id'],
        ondelete='SET NULL',
    )
    op.create_foreign_key(
        'fk_payroll_runs_lifecycle_approved_by',
        'payroll_runs',
        'users',
        ['lifecycle_approved_by'],
        ['user_id'],
        ondelete='SET NULL',
    )
    op.create_foreign_key(
        'fk_payroll_runs_lifecycle_locked_by',
        'payroll_runs',
        'users',
        ['lifecycle_locked_by'],
        ['user_id'],
        ondelete='SET NULL',
    )
    op.create_table('work_locations',
    sa.Column('location_id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False),
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), server_default=sa.text("'India'"), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('(true)'), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.organisation_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('location_id'),
    sa.UniqueConstraint('organisation_id', 'name', name='ux_worklocations_org_name')
    )
    op.create_table('pay_structures',
    sa.Column('pay_structure_id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False),
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.organisation_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['salary_templates.template_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('pay_structure_id'),
    sa.UniqueConstraint('organisation_id', 'name', name='ux_paystructures_org_name')
    )
    op.create_table('payroll_lifecycle_audit',
    sa.Column('audit_id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False),
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.organisation_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('audit_id')
    )
    op.create_table('salary_component_group_items',
    sa.Column('id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('component_id', sa.UUID(), nullable=False),
    sa.Column('sequence', sa.SmallInteger(), server_default=sa.text('1'), nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['salary_components.component_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['group_id'], ['salary_component_groups.group_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'component_id', name='ux_salary_component_group_items_group_component')
    )
    op.create_table('salary_component_group_versions',
    sa.Column('group_version_id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False),
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('(true)'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.CheckConstraint('effective_to IS NULL OR effective_to >= effective_from', name='ck_scgv_effective_range'),
    sa.ForeignKeyConstraint(['group_id'], ['salary_component_groups.group_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.organisation_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('group_version_id')
    )
    op.create_table('salary_component_versions',
    sa.Column('version_id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False),
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('component_id', sa.UUID(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('component_category', sa.String(length=30), nullable=True),
    sa.Column('calculation_type', sa.String(length=20), nullable=True),
    sa.Column('formula_expression', sa.Text(), nullable=True),
    sa.Column('system_code', sa.String(length=30), nullable=True),
    sa.Column('rounding_rule', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("('{}'::jsonb)"), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("('{}'::jsonb)"), nullable=False),
    sa.Column('component_type', sa.String(length=50), nullable=False),
    sa.Column('calc_type', sa.String(length=20), server_default=sa.text("'fixed'"), nullable=False),
    sa.Column('percentage_of', sa.String(length=100), nullable=True),
    sa.Column('formula', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('(true)'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.CheckConstraint('effective_to IS NULL OR effective_to >= effective_from', name='ck_scv_effective_range'),
    sa.ForeignKeyConstraint(['component_id'], ['salary_components.component_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.organisation_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('version_id')
    )
    op.create_table('salary_derived_variable_versions',
    sa.Column('version_id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False),
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('variable_id', sa.UUID(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('expression', sa.Text(), nullable=False),
    sa.Column('data_type', sa.String(length=10), server_default=sa.text("'number'"), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('(true)'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.CheckConstraint('effective_to IS NULL OR effective_to >= effective_from', name='ck_sdv_effective_range'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.organisation_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variable_id'], ['salary_derived_variables.variable_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('version_id')
    )
    op.create_table('salary_template_components',
    sa.Column('stc_id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('component_id', sa.UUID(), nullable=False),
    sa.Column('sequence', sa.SmallInteger(), server_default=sa.text('1'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('percentage', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('percentage_of', sa.String(length=100), nullable=True),
    sa.Column('formula', sa.Text(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("('{}'::jsonb)"), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('(true)'), nullable=False),
    sa.CheckConstraint('percentage IS NULL OR (percentage >= 0 AND percentage <= 100)', name='chk_percentage_range'),
    sa.ForeignKeyConstraint(['component_id'], ['salary_components.component_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['template_id'], ['salary_templates.template_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('stc_id'),
    sa.UniqueConstraint('template_id', 'component_id', name='ux_stc_template_component')
    )
    op.create_table('salary_template_groups',
    sa.Column('id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('sequence', sa.SmallInteger(), server_default=sa.text('1'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('(true)'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['salary_component_groups.group_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['template_id'], ['salary_templates.template_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_id', 'group_id', name='ux_salary_template_groups_template_group')
    )
    op.create_table('salary_template_versions',
    sa.Column('template_version_id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False),
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('label', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("('{}'::jsonb)"), nullable=False),
    sa.CheckConstraint('effective_to IS NULL OR effective_to >= effective_from', name='ck_stv_effective_range'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.organisation_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['salary_templates.template_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('template_version_id')
    )
    op.create_table('user_roles',
    sa.Column('user_role_id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('assigned_by', sa.UUID(), nullable=True),
    sa.Column('assigned_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_role_id'),
    sa.UniqueConstraint('user_id', 'role_id', name='ux_user_roles_user_role')
    )
    op.create_table('employees',
    sa.Column('employee_id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False),
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('employee_code', sa.String(length=100), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('middle_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('work_email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('mobile_phone', sa.String(length=30), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('marital_status', sa.String(length=20), nullable=True),
    sa.Column('fathers_name', sa.String(length=100), nullable=True),
    sa.Column('date_of_joining', sa.Date(), nullable=True),
    sa.Column('date_of_leaving', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'active'"), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=True),
    sa.Column('designation_id', sa.UUID(), nullable=True),
    sa.Column('location_id', sa.UUID(), nullable=True),
    sa.Column('business_unit', sa.String(length=100), nullable=True),
    sa.Column('manager_id', sa.UUID(), nullable=True),
    sa.Column('pay_structure_id', sa.UUID(), nullable=True),
    sa.Column('annual_ctc', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('pay_frequency', sa.String(length=20), server_default=sa.text("'Monthly'"), nullable=True),
    sa.Column('uan_link_status', sa.String(length=50), server_default=sa.text("'Unlinked'"), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('(true)'), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('is_password_changed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.department_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['designation_id'], ['designations.designation_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['location_id'], ['work_locations.location_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['manager_id'], ['employees.employee_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.organisation_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pay_structure_id'], ['pay_structures.pay_structure_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('employee_id'),
    sa.UniqueConstraint('organisation_id', 'email', name='ux_employees_org_email'),
    sa.UniqueConstraint('organisation_id', 'employee_code', name='ux_employees_org_code')
    )
    op.create_table('salary_component_group_item_versions',
    sa.Column('id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False),
    sa.Column('group_version_id', sa.UUID(), nullable=False),
    sa.Column('component_id', sa.UUID(), nullable=False),
    sa.Column('sequence', sa.SmallInteger(), server_default=sa.text('1'), nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['salary_components.component_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['group_version_id'], ['salary_component_group_versions.group_version_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_version_id', 'component_id', name='ux_scgiv_ver_component')
    )
    op.create_table('salary_preview_snapshots',
    sa.Column('snapshot_id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False),
    sa.Column('trace_id', sa.UUID(), nullable=False),
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('template_version_id', sa.UUID(), nullable=True),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('ctc', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=True),
    sa.Column('overrides', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("('{}'::jsonb)"), nullable=False),
    sa.Column('resolved_versions', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("('{}'::jsonb)"), nullable=False),
    sa.Column('resolved_dag', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("('{}'::jsonb)"), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("('{}'::jsonb)"), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.organisation_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['salary_templates.template_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_version_id'], ['salary_template_versions.template_version_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('snapshot_id')
    )
    op.create_table('salary_template_component_versions',
    sa.Column('id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False),
    sa.Column('template_version_id', sa.UUID(), nullable=False),
    sa.Column('component_id', sa.UUID(), nullable=False),
    sa.Column('sequence', sa.SmallInteger(), server_default=sa.text('1'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('percentage', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('percentage_of', sa.String(length=100), nullable=True),
    sa.Column('formula', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('(true)'), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("('{}'::jsonb)"), nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['salary_components.component_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['template_version_id'], ['salary_template_versions.template_version_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_version_id', 'component_id', name='ux_stcv_tplver_component')
    )
    op.create_table('salary_template_group_versions',
    sa.Column('id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False),
    sa.Column('template_version_id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('sequence', sa.SmallInteger(), server_default=sa.text('1'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('(true)'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['salary_component_groups.group_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['template_version_id'], ['salary_template_versions.template_version_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_version_id', 'group_id', name='ux_stgv_tplver_group')
    )
    op.create_table('employee_documents',
    sa.Column('document_id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.String(length=100), nullable=True),
    sa.Column('document_url', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('uploaded_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.organisation_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('document_id')
    )
    op.create_table('employee_leave_balances',
    sa.Column('balance_id', sa.UUID(), nullable=False),
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('leave_type', sa.String(length=10), nullable=False),
    sa.Column('period_year', sa.Integer(), nullable=False),
    sa.Column('opening_balance', sa.Numeric(precision=8, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('accrued', sa.Numeric(precision=8, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('consumed', sa.Numeric(precision=8, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('carried_forward', sa.Numeric(precision=8, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('encashed', sa.Numeric(precision=8, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("leave_type IN ('CL','SL','EL','LOP')", name='ck_employee_leave_balances_leave_type'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.organisation_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('balance_id'),
    sa.UniqueConstraint('employee_id', 'leave_type', 'period_year', name='ux_emp_leave_year')
    )
    op.create_index('ix_leave_balances_org_emp', 'employee_leave_balances', ['organisation_id', 'employee_id'], unique=False)
    op.create_table('employee_salary_assignments',
    sa.Column('salary_assignment_id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('pay_structure_id', sa.UUID(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pay_structure_id'], ['pay_structures.pay_structure_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('salary_assignment_id'),
    sa.UniqueConstraint('employee_id', 'effective_from', name='ux_emp_effective_from')
    )
    op.create_table('employee_salary_structures',
    sa.Column('id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('ctc', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('overrides', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("('{}'::jsonb)"), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.organisation_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['salary_templates.template_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'effective_from', name='ux_employee_salary_effective')
    )
    op.create_table('leaves',
    sa.Column('leave_id', sa.UUID(), nullable=False),
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('leave_type', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('days', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('applied_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approved_on', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['cancelled_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.organisation_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('leave_id'),
    sa.UniqueConstraint('employee_id', 'start_date', 'end_date', name='uq_employee_leave_dates')
    )
    op.create_index('ix_leaves_org_dates', 'leaves', ['organisation_id', 'start_date', 'end_date'], unique=False)
    op.create_index('ix_leaves_org_emp_status', 'leaves', ['organisation_id', 'employee_id', 'status'], unique=False)
    op.create_table('payroll_entries',
    sa.Column('payroll_entry_id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False),
    sa.Column('payroll_run_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('component_id', sa.UUID(), nullable=False),
    sa.Column('pay_period_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['salary_components.component_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pay_period_id'], ['pay_periods.pay_period_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['payroll_run_id'], ['payroll_runs.payroll_run_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('payroll_entry_id'),
    sa.UniqueConstraint('payroll_run_id', 'employee_id', 'component_id', name='ux_payrollentries_run_emp_comp')
    )
    op.create_table('attendances',
    sa.Column('attendance_id', sa.UUID(), nullable=False),
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('work_date', sa.Date(), nullable=False),
    sa.Column('time_in', sa.DateTime(timezone=True), nullable=True),
    sa.Column('time_out', sa.DateTime(timezone=True), nullable=True),
    sa.Column('work_hours', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('day_fraction', sa.Numeric(precision=5, scale=4), server_default='1.0', nullable=False),
    sa.Column('is_locked', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('salary_assignment_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.organisation_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['salary_assignment_id'], ['employee_salary_assignments.salary_assignment_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('attendance_id'),
    sa.UniqueConstraint('employee_id', 'work_date', name='uq_employee_workdate')
    )
    op.create_index('ix_attendances_org_emp_date', 'attendances', ['organisation_id', 'employee_id', 'work_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_attendances_org_emp_date', table_name='attendances')
    op.drop_table('attendances')
    op.drop_table('payroll_entries')
    op.drop_index('ix_leaves_org_emp_status', table_name='leaves')
    op.drop_index('ix_leaves_org_dates', table_name='leaves')
    op.drop_table('leaves')
    op.drop_table('employee_salary_structures')
    op.drop_table('employee_salary_assignments')
    op.drop_index('ix_leave_balances_org_emp', table_name='employee_leave_balances')
    op.drop_table('employee_leave_balances')
    op.drop_table('employee_documents')
    op.drop_table('salary_template_group_versions')
    op.drop_table('salary_template_component_versions')
    op.drop_table('salary_preview_snapshots')
    op.drop_table('salary_component_group_item_versions')
    op.drop_table('employees')
    op.drop_table('user_roles')
    op.drop_table('salary_template_versions')
    op.drop_table('salary_template_groups')
    op.drop_table('salary_template_components')
    op.drop_table('salary_derived_variable_versions')
    op.drop_table('salary_component_versions')
    op.drop_table('salary_component_group_versions')
    op.drop_table('salary_component_group_items')
    op.drop_table('payroll_lifecycle_audit')
    op.drop_table('pay_structures')
    op.drop_table('work_locations')
    # pay_periods -> payroll_runs optional FK must be removed before dropping either side
    op.drop_constraint('fk_pay_periods_locked_by_run', 'pay_periods', type_='foreignkey')
    op.drop_table('payroll_runs')
    op.drop_table('pay_periods')
    op.drop_table('users')
    op.drop_table('salary_templates')
    op.drop_table('salary_derived_variables')
    op.drop_table('salary_components')
    op.drop_table('salary_component_groups')
    op.drop_table('roles')
    op.drop_index('ix_org_holidays_org_date', table_name='organisation_holidays')
    op.drop_table('organisation_holidays')
    op.drop_table('org_statutory_configs')
    op.drop_table('designations')
    op.drop_table('departments')
    op.drop_table('organisations')
    op.drop_table('api_idempotency_keys')
    # ### end Alembic commands ###
