"""add reset password fields

Revision ID: be0ad63ad68d
Revises: ede906d3a47b
Create Date: 2026-03-15 11:02:53.670119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'be0ad63ad68d'
down_revision: Union[str, Sequence[str], None] = 'ede906d3a47b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employee_statutory_details')
    op.drop_table('loan_types')
    op.drop_table('employee_bank_details')
    op.drop_table('statutory_settings')
    op.drop_table('audit_logs')
    op.drop_table('loan_requests')
    op.drop_table('payment_batches')
    op.drop_table('payroll_entries')
    op.drop_table('pay_periods')
    op.drop_table('bank_file_formats')
    op.drop_table('payroll_runs')
    op.drop_table('payroll_tax_summaries')
    op.drop_table('tax_declarations')
    op.add_column('attendances', sa.Column('salary_assignment_id', sa.UUID(), nullable=True))
    op.alter_column('attendances', 'work_hours',
               existing_type=sa.NUMERIC(precision=6, scale=2),
               type_=sa.Float(),
               nullable=False)
    op.create_foreign_key(None, 'attendances', 'employee_salary_assignments', ['salary_assignment_id'], ['salary_assignment_id'], ondelete='CASCADE')
    op.alter_column('employee_salary_structures', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_unique_constraint('ux_employee_salary_effective', 'employee_salary_structures', ['employee_id', 'effective_from'])
    op.drop_column('employees', 'joining_date')
    op.alter_column('salary_components', 'is_taxable',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('salary_components', 'is_pf_applicable',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('salary_components', 'is_allowance',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('salary_components', 'is_loan_related',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'reset_token',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('users', 'reset_token_expiry',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.TIMESTAMP(timezone=True),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'reset_token_expiry',
               existing_type=sa.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('users', 'reset_token',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('salary_components', 'is_loan_related',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('salary_components', 'is_allowance',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('salary_components', 'is_pf_applicable',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('salary_components', 'is_taxable',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.add_column('employees', sa.Column('joining_date', sa.DATE(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_constraint('ux_employee_salary_effective', 'employee_salary_structures', type_='unique')
    op.alter_column('employee_salary_structures', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'attendances', type_='foreignkey')
    op.alter_column('attendances', 'work_hours',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=6, scale=2),
               nullable=True)
    op.drop_column('attendances', 'salary_assignment_id')
    op.create_table('tax_declarations',
    sa.Column('declaration_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('employee_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('financial_year', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('section', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('declared_amount', sa.NUMERIC(precision=18, scale=4), autoincrement=False, nullable=False),
    sa.Column('approved_amount', sa.NUMERIC(precision=18, scale=4), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('submitted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('approved_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('approved_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.user_id'], name=op.f('tax_declarations_approved_by_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], name=op.f('tax_declarations_employee_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('declaration_id', name=op.f('tax_declarations_pkey'))
    )
    op.create_table('payroll_tax_summaries',
    sa.Column('tax_summary_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('payroll_run_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('employee_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tds_amount', sa.NUMERIC(precision=18, scale=4), autoincrement=False, nullable=False),
    sa.Column('employee_pf', sa.NUMERIC(precision=18, scale=4), autoincrement=False, nullable=False),
    sa.Column('employer_pf', sa.NUMERIC(precision=18, scale=4), autoincrement=False, nullable=False),
    sa.Column('professional_tax', sa.NUMERIC(precision=18, scale=4), autoincrement=False, nullable=False),
    sa.Column('employer_esi', sa.NUMERIC(precision=18, scale=4), autoincrement=False, nullable=False),
    sa.Column('employee_esi', sa.NUMERIC(precision=18, scale=4), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], name=op.f('payroll_tax_summaries_employee_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['payroll_run_id'], ['payroll_runs.payroll_run_id'], name=op.f('payroll_tax_summaries_payroll_run_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tax_summary_id', name=op.f('payroll_tax_summaries_pkey')),
    sa.UniqueConstraint('payroll_run_id', 'employee_id', name=op.f('ux_payroll_run_employee'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('payroll_runs',
    sa.Column('payroll_run_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('organisation_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('pay_period_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('processed_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('processed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'draft'::character varying"), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('net_pay_total', sa.NUMERIC(precision=18, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('gross_pay_total', sa.NUMERIC(precision=18, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.organisation_id'], name=op.f('payroll_runs_organisation_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pay_period_id'], ['pay_periods.pay_period_id'], name=op.f('payroll_runs_pay_period_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['processed_by'], ['users.user_id'], name=op.f('payroll_runs_processed_by_fkey')),
    sa.PrimaryKeyConstraint('payroll_run_id', name=op.f('payroll_runs_pkey'))
    )
    op.create_table('bank_file_formats',
    sa.Column('format_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('organisation_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('bank_code', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('bank_name', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('branch_code', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('file_type', postgresql.ENUM('CSV', 'TXT', 'XML', name='bank_file_type_t'), autoincrement=False, nullable=False),
    sa.Column('header_line', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('data_line_config', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.organisation_id'], name=op.f('bank_file_formats_organisation_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('format_id', name=op.f('bank_file_formats_pkey')),
    sa.UniqueConstraint('organisation_id', 'bank_code', 'name', name=op.f('uq_bank_format'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('pay_periods',
    sa.Column('pay_period_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('organisation_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'open'::character varying"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.organisation_id'], name=op.f('pay_periods_organisation_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pay_period_id', name=op.f('pay_periods_pkey')),
    sa.UniqueConstraint('organisation_id', 'start_date', 'end_date', name=op.f('ux_pay_periods_org_dates'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('payroll_entries',
    sa.Column('payroll_entry_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('payroll_run_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('employee_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('component_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('pay_period_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=18, scale=4), autoincrement=False, nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['salary_components.component_id'], name=op.f('payroll_entries_component_id_fkey'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], name=op.f('payroll_entries_employee_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pay_period_id'], ['pay_periods.pay_period_id'], name=op.f('payroll_entries_pay_period_id_fkey'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['payroll_run_id'], ['payroll_runs.payroll_run_id'], name=op.f('payroll_entries_payroll_run_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('payroll_entry_id', name=op.f('payroll_entries_pkey')),
    sa.UniqueConstraint('payroll_run_id', 'employee_id', 'component_id', name=op.f('ux_payrollentries_run_emp_comp'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('payment_batches',
    sa.Column('batch_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('payroll_run_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('format_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('file_name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('upload_path', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('total_employees', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_amount', sa.NUMERIC(precision=18, scale=4), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('Generated', 'Uploaded', 'Rejected', 'Paid', name='payment_status_t'), autoincrement=False, nullable=False),
    sa.Column('uploaded_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('paid_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('transaction_ref', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('rejection_reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['format_id'], ['bank_file_formats.format_id'], name=op.f('payment_batches_format_id_fkey'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['payroll_run_id'], ['payroll_runs.payroll_run_id'], name=op.f('payment_batches_payroll_run_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.user_id'], name=op.f('payment_batches_uploaded_by_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('batch_id', name=op.f('payment_batches_pkey')),
    sa.UniqueConstraint('payroll_run_id', 'format_id', name=op.f('uq_payment_batch_run_format'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('loan_requests',
    sa.Column('request_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('organisation_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('employee_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('loan_type_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('requested_amount', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=False),
    sa.Column('requested_installments', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('purpose', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('reviewed_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('reviewed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('remarks', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], name=op.f('loan_requests_employee_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['loan_type_id'], ['loan_types.loan_type_id'], name=op.f('loan_requests_loan_type_id_fkey'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.organisation_id'], name=op.f('loan_requests_organisation_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.user_id'], name=op.f('loan_requests_reviewed_by_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('request_id', name=op.f('loan_requests_pkey'))
    )
    op.create_table('audit_logs',
    sa.Column('log_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('organisation_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('action', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('entity', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('entity_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('occurred_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.organisation_id'], name=op.f('audit_logs_organisation_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('audit_logs_user_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('log_id', name=op.f('audit_logs_pkey'))
    )
    op.create_table('statutory_settings',
    sa.Column('statutory_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('organisation_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('statutory_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('registration_no', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('employer_contribution', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('employee_contribution', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('additional_info', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('effective_from', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('effective_to', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint('employee_contribution >= 0::numeric AND employee_contribution <= 100::numeric', name=op.f('chk_employee_contribution_range')),
    sa.CheckConstraint('employer_contribution >= 0::numeric AND employer_contribution <= 100::numeric', name=op.f('chk_employer_contribution_range')),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.organisation_id'], name=op.f('statutory_settings_organisation_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('statutory_id', name=op.f('statutory_settings_pkey')),
    sa.UniqueConstraint('organisation_id', 'statutory_type', 'effective_from', name=op.f('ux_statutory_org_type_from'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('employee_bank_details',
    sa.Column('bank_detail_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('employee_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('bank_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('account_number', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('ifsc_code', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('is_primary', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('effective_from', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('effective_to', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], name=op.f('employee_bank_details_employee_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('bank_detail_id', name=op.f('employee_bank_details_pkey')),
    sa.UniqueConstraint('employee_id', 'effective_from', name=op.f('uq_bank_employee_from'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('loan_types',
    sa.Column('loan_type_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('organisation_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('max_amount', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=True),
    sa.Column('max_installments', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('interest_rate', sa.NUMERIC(precision=6, scale=3), autoincrement=False, nullable=True),
    sa.Column('is_interest_applicable', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_salary_advance', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.organisation_id'], name=op.f('loan_types_organisation_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('loan_type_id', name=op.f('loan_types_pkey')),
    sa.UniqueConstraint('organisation_id', 'name', name=op.f('uq_loan_type_org_name'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('employee_statutory_details',
    sa.Column('stat_detail_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('employee_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('pan_number', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('uan_number', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('esi_number', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('pt_location', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('tax_regime', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.VARCHAR(length=5), autoincrement=False, nullable=False),
    sa.Column('effective_from', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], name=op.f('employee_statutory_details_employee_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('stat_detail_id', name=op.f('employee_statutory_details_pkey')),
    sa.UniqueConstraint('employee_id', 'effective_from', name=op.f('ux_employee_stat_effective_from'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('pan_number', name=op.f('employee_statutory_details_pan_number_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
